# fly.toml app configuration file generated for scholia on 2023-05-28T16:38:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scholia"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
